version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .web.env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=task_over_flow
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
  frontend:
    build: ./src/main/typescript
    ports:
      - "4200:4200"
    volumes:
        - ./src/main/typescript:/app
